apiVersion: v1
kind: ConfigMap
metadata:
  name: config-app1-test
  namespace: ns-app1
data:
  app.config: |
    environment=dev
    mode=strict
    sql-target=mysql.server.com
  app.config2: |
    color_scheme=dark
    easter_egg=on
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-sindre-troubleshoot
  namespace: ns-app1
spec:
  selector:
    matchLabels:
      app: sindre-troubleshoot
  replicas: 1
  template:
    metadata:
      labels:
        app: sindre-troubleshoot
    spec:
      containers:
      - name: sindre-troubleshoot-container
        image: wbitt/network-multitool
        ports:
        - containerPort: 80
        volumeMounts:
        - name: volume-config-app1-test
          mountPath: /config/
    volumes:
    - name: "volume-config-app1-test"
      configMap:
        name: config-app1-test
---
