apiVersion: apps/v1
kind: Deployment
metadata:
  name: klient-deployment
  namespace: ns-app1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapi
  template:
    metadata:
      labels:
        app: webapi
    spec:
      imagePullSecrets:
      - name: myregistrykey
      containers:
      - name: webapi-container
        image: acrvmwarepoc01.azurecr.io/server:latest
        ports:
        - containerPort: 8080        
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: AKS   

---
apiVersion: v1
kind: Service
metadata:
  name: webapi-service
  namespace: ns-app1
spec:
  type: LoadBalancer
  selector:
    app: webapi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

