apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment.app1.web.1
  namespace: ns-app1
spec:
  selector:
    matchLabels:
      app: flux-app1-web
  replicas: 2
  template:
    metadata:
      labels:
        app: flux-app1-web
    spec:
      containers:
      - name: flux-app1-web-container
        image: yeasy/simple-web:latest
        ports:
        - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: service-app1-web
  namespace: ns-app1
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: flux-app1-web

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-app1-web
  namespace: ns-app1
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: fhi-k8s-letsencrypt-azuredns-issuer
spec:
  ingressClassName: nginx
  rules:
  - host: sindre-app1.fhi-k8s.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: service-app1-web
            port:
              number: 80
      - path: /static/
        pathType: Prefix
        backend:
          service:
            name: service-app1-static
            port:
              number: 80
  tls:
    - hosts:
        - sindre-app1.fhi-k8s.com
      secretName: tls-app1
          


