apiVersion: apps/v1
kind: Deployment
metadata:
  name: flux-app1-deployment
  namespace: ns-app1
spec:
  selector:
    matchLabels:
      app: flux-app1-web
  replicas: 1
  template:
    metadata:
      labels:
        app: flux-app1-web
    spec:
      containers:
      - name: flux-app1-web-container
        image: yeasy/simple-web:latest
        ports:
        - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: service-app1-web
  namespace: ns-app1
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: flux-app1-web

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-app1-web
  namespace: ns-app1
spec:
#  ingressClassName: webapprouting.kubernetes.azure.com
  rules:
  - host: app1.k8s.fhi-api.com
    http:
      paths:
      - backend:
          service:
            name: service-app1-web
            port:
              number: 80
        path: /
        pathType: Prefix

