apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-demo-test
  namespace: ns-app1
spec:
  selector:
    matchLabels:
      app: demo-test
  replicas: 5
  template:
    metadata:
      labels:
        app: demo-test
    spec:
      containers:
      - name: demo-test-container
        image: yeasy/simple-web:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: service-demo-test
  namespace: ns-app1
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: demo-test
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-demo-test
  namespace: ns-app1
  annotations:
    external-dns.alpha.kubernetes.io/target: 83.118.177.220
    cert-manager.io/cluster-issuer: fhi-k8s-letsencrypt-azuredns-issuer
spec:
  ingressClassName: nginx
  rules:
  - host: demo-test.fhi-k8s.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: service-demo-test
            port:
              number: 80
  tls:
    - hosts:
        - demo-test.fhi-k8s.com
      secretName: tls-demo-test