apiVersion: apps/v1
kind: Deployment
metadata:
  name: flux-app1-deployment
  namespace: ns-app1
spec:
  selector:
    matchLabels:
      app: flux-app1-nginx
  replicas: 6
  template:
    metadata:
      labels:
        app: flux-app1-nginx
    spec:
      containers:
      - name: flux-app1-nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: service-app1-nginx
  namespace: ns-app1
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: flux-app1-nginx

---

