apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-demo
  namespace: ns-app1
spec:
  selector:
    matchLabels:
      app: demo
  replicas: 1
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - name: demo-container
        image: tutum/hello-world
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: service-demo
  namespace: ns-app1
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: demo
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-demo
  namespace: ns-app1
  annotations:
    cert-manager.io/cluster-issuer: fhi-k8s-letsencrypt-azuredns-issuer
spec:
  ingressClassName: nginx
  rules:
  - host: demo.fhi-k8s.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: service-demo
            port:
              number: 80
  tls:
    - hosts:
        - demo.fhi-k8s.com
      secretName: tls-demo
