apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-sindre-troubleshoot
  namespace: ns-app1
spec:
  selector:
    matchLabels:
      app: sindre-troubleshoot
  replicas: 1
  template:
    metadata:
      labels:
        app: sindre-troubleshoot
    spec:
      containers:
      - name: sindre-troubleshoot-container
        image: wbitt/network-multitool
        ports:
        - containerPort: 80