apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-sindre-troubleshoot
  namespace: ns-app1
spec:
  selector:
    matchLabels:
      app: sindre-troubleshoot
  replicas: 1
  template:
    metadata:
      labels:
        app: sindre-troubleshoot
    spec:
      containers:
      - name: sindre-troubleshoot-container
        image: wbitt/network-multitool
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: service-sindre-troubleshoot
  namespace: ns-app1
  annotations:
    cert-manager.io/cluster-issuer: fhi-k8s-letsencrypt-azuredns-issuer
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: sindre-troubleshoot
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-sindre-troubleshoot
  namespace: ns-app1
spec:
  ingressClassName: nginx
  rules:
  - host: sindre-troubleshoot.fhi-k8s.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: service-sindre-troubleshoot
            port:
              number: 80
  tls:
    - hosts:
        - sindre-troubleshoot.fhi-k8s.com
      secretName: tls-app1-static