apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-tenant5-1
  namespace: nfs
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-csi
  resources:
    requests:
      storage: 10Gi