apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-appnavn
  namespace: ns-appnavn
spec:
  selector:
    matchLabels:
      app: app-appnavn
  replicas: 2
  template:
    metadata:
      labels:
        app: app-appnavn
    spec:
      containers:
      - name: appnavn-container
        image: tutum/hello-world
        ports:
        - containerPort: 80