apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-app
data:
  app.config: |
    environment=dev
    mode=strict
    sql-target=mysql.server.com
  app.config2: |
    color_scheme=dark
    easter_egg=on