apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-appnavn
  namespace: ns-appnavn
spec:
  template:
    spec:
      containers:
      - name: appnavn-container
        image: tutum/hello-world
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
        volumeMounts:
        - name: volume-config-app
          mountPath: /fhi_config/
      volumes:
      - name: "volume-config-app"
        configMap:
          name: configmap-app-dev
    replicas: 1