apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-appnavn
  namespace: ns-appnavn
spec:
  template:
    spec:
      containers:
      - name: appnavn-container
        image: tutum/hello-world
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
        volumeMounts:
        - name: volume-config-app
          mountPath: /fhi_config/
        - name: volume-akv-secret-1
          mountPath: /fhi_secret/
      volumes:
      - name: "volume-config-app"
        configMap:
          name: configmap-app-dev
      - name: "volume-akv-secret-1"
        csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "azure-kv-k8s-test-dev"
            nodePublishSecretRef:
              name: secret-azure-kv-k8s-test-dev            # Secret name for service principal info
    replicas: 1