apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: kustomize-app12-dev
resources:
- ../base
- configmap.yaml
- akv-store.yaml
- mtls-certificate.yaml
- mtls-certificate2.yaml
nameSuffix: -dev
namespace: ns-app12-dev
commonLabels:
  app: app-app12-dev
#images:
#- name: nginx
#  newName: my.image.registry/nginx
#  newTag: 1.4.0
patchesStrategicMerge:
  - deployment-patch.yaml
  - hpa-patch.yaml