apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mtls-service-appnavn3
  namespace: ns-appnavn
spec:
  secretName: mtls-service-appnavn3-dev
  #additionalOutputFormats:
  #- type: CombinedPEM
  #- type: DER

  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048

  duration: 2160h # 90d
  renewBefore: 360h # 15d

  isCA: false
  usages:
    - server auth
    - client auth

  subject:
    organizations:
      - cert-manager

  dnsNames:
    - service-appnavn.ns-appnavn-dev.svc.cluster.local
    - localhost

  issuerRef:
    name: cluster-selfsigned-ca-issuer
    kind: ClusterIssuer